config/routes.rb
Rails.application.routes.draw do

  root 'poll#index'
  post '/poll/create' , to: 'poll#create', as: 'poll_create'
  get '/poll/new', to:'poll#new', as: 'poll_new'
  get '/poll/show/:id', to:'poll#show', as: 'poll_show'
  post '/poll/vote', to:'poll#vote', as: 'poll_vote'
  get '/poll/index', to:'poll#index', as: 'poll_index'
  get '/poll/show_vote/:id', to:'poll#show_vote', as: 'poll_show_vote'

  # resources :polls
end

app/models/choice.rb
class Choice < ActiveRecord::Base
	belongs_to :poll
end

app/models/poll.rb
class Poll < ActiveRecord::Base
	#has_one :selected_choice
	has_many :choices

	belongs_to :selected_choice, class_name:'Choice', :foreign_key => :selected_choice_id
	
	accepts_nested_attributes_for :choices
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poll_controller.rb
class PollController < ApplicationController
	def create
		@poll = Poll.new		
		
	end

	def index
		@poll = Poll.new		
		
	end
	

	def new

		@poll = Poll.new
  		4.times { @poll.choices.build }
		#poll = Poll.new( name: params[:poll] [:name] )
		

	end

		#@poll = Poll.new
		#if poll.save
			#Todo: redirect to this user (show user)
			#redirect_to poll_show_path(poll.id)

			#puts "1111111111111111111111111"
			#render nothing: true
		#else
			#redirect_to poll_new_path			#puts "2222222222222222222222222"
		#end
	#end

	def show
		@poll = Poll.find(params[:id])
	end

	#def show
		#poll = Poll.new(name: params[:poll])
			#name: params[:poll] [:name],name: params[:poll] [:name])

		#@poll = Poll.find(params[:id])
		#poll = Poll.new( name: params[:poll] )
		#@poll = Poll.find(params[:id])
	#end

	#def two

		#@poll = Poll.new(name: params[:poll])
		#@poll = Poll.new
  		#4.times { @poll.choice.build }

	#end

	def vote
		puts "XXXXX" + params.to_s
  		#@poll = Poll.new(choice_params)
		@poll = Poll.find(params[:id])
		@poll.selected_choice_id = params[:radio]
  	
		if @poll.save
			redirect_to poll_show_vote_path(@poll.id)
		else
			redirect_to poll_show_path	
		end		
		
  	end

	def create

		@poll = Poll.new(poll_params)
		
  		#4.times { @poll.choice.build }
  		#puts params.to_h
		#poll = Poll.new(name: params[:poll][:name])
		#poll.choices = params[:poll][:choices]
		 

		#poll = params.require(:poll).permit(:name,:Cone, :Ctwo, :Cthree,:Cfour )
		 #choices_attributes: [:id,:Cone, :Ctwo, :Cthree])
		#poll.choices = params[:poll][:choices]

		if @poll.save
			redirect_to poll_show_path(@poll.id)
		else
			redirect_to poll_new_path	
		end
	end
	
  	def show_vote
		@poll = Poll.find(params[:id])
	end

	private

  	def poll_params
    	params.require(:poll).permit(:name, choices_attributes: [:name])
  	end

  	def choice_params
    	params.require(:choice).permit(:name, choices_attributes: [:name])
  	end

  	



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poll_helper.rb
module PollHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPoll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poll/create_session.html.erb
<b>Name: </b><%= @name %><br>

app/views/poll/index.html.erb
 <%= form_for @poll, method: :get, url: poll_new_path do |f| %>


  <%= f.submit "Createppppppp" %>


<% end %>

app/views/poll/new.html.erb
<%= form_for @poll, method: :post, url: poll_create_path do |f| %>

	<%= f.label :Poll %><br>
  <%= f.text_field :name %><br>

Choices:

	<ul>
    <%= f.fields_for :choices do |choice_form| %>
      <li>

        <%= choice_form.label :Choice %><br>
        <%= choice_form.text_field :name %><br>  


      </li>
    <% end %>
  	</ul>
  
 <br><%= f.submit 'Create' %>


<% end %>

app/views/poll/show.html.erb
<%= form_for @poll , method: :post, url: poll_vote_path do |f| %>
	<b>Poll : </b><%= @poll.name %><br>
	<%= hidden_field_tag :id, @poll.id %>

	<% @poll.choices.each do |choice|%>

    <%= radio_button_tag(:radio, choice.id) %>
    <%= label_tag(:tag, choice.name) %><br>
    
    <% end %>

  	 <br><%= f.submit "Vote" %>

<% end %>

app/views/poll/show_vote.html.erb
<b>Poll : </b><%= @poll.name %><br>
<b>Choice : </b><%= @poll.selected_choice.name %><br> 

app/views/poll/two.html.erb
<%= form_for @poll, method: :post, url: poll_create_session_path do |f| %>
	<%= f.label :Poll %><br>
    <%= f.text_field :name %><br>
Choices:
	<ul>
    <%= f.fields_for :choice do |choice_form| %>
      <li>
      	
        <%= choice_form.label :Choice1 %><br>
        <%= choice_form.text_field :name %><br>
 
        <%= choice_form.label :Choice2 %><br>
        <%= choice_form.text_field :name %><br>

        <%= choice_form.label :Choice3 %><br>
        <%= choice_form.text_field :name %><br>

        <%= choice_form.label :Choice4 %><br>
        <%= choice_form.text_field :name %><br>
        
      </li>
    <% end %>
  	</ul>
  
 <br><%= f.submit 'Create' %>


<% end %>